version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "user_db"
      MYSQL_ROOT_PASSWORD: "Vaish@099"
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose Spring Boot app on port 8080
    environment:
      SPRING_APPLICATION_NAME: "SpringSecurityExample"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/userdetails"  # Use mysql as host name
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Vaish@099"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql  # Ensure MySQL starts before the Spring Boot app
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local  # Volume to persist MySQL data

networks:
  app-network:
    driver: bridge  # Custom network for communication between services
